import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const EXAMPLES_DIR = path.join(__dirname, '../public/examples');

export const MCAP_BASIC = path.join(EXAMPLES_DIR, 'test_5s.mcap');
export const MCAP_POSE = path.join(EXAMPLES_DIR, 'test_pose.mcap');
export const MCAP_3CAM = path.join(EXAMPLES_DIR, 'test_3cam.mcap');
export const MCAP_H264 = path.join(EXAMPLES_DIR, 'test_h264.mcap');
export const MCAP_COMPRESSED_DEPTH = path.join(EXAMPLES_DIR, 'test_compressed_depth.mcap');
export const HDF5_MINIMAL = path.join(EXAMPLES_DIR, 'test_minimal.hdf5');
export const BVH_MINIMAL = path.join(EXAMPLES_DIR, 'test_minimal.bvh');

/** Multi-source merge fixtures (see scripts/gen-test-mcap-multi-*.mjs). */
export const MCAP_MULTI_BASE = path.join(EXAMPLES_DIR, 'test_multi_base.mcap');
export const MCAP_MULTI_INCREMENTAL = path.join(EXAMPLES_DIR, 'test_multi_incremental.mcap');
/** Derived from MCAP_MULTI_BASE via the real `mcap filter` CLI; absent if the CLI isn't installed. */
export const MCAP_MULTI_FILTERED = path.join(EXAMPLES_DIR, 'test_multi_filtered.mcap');
/** Generated by scripts/gen-test-bag.py (Python `rosbags`); absent if that package isn't installed. */
export const BAG_MULTI = path.join(EXAMPLES_DIR, 'test_multi.bag');

export const MCAP_BASIC_URL = '/examples/test_5s.mcap';
export const MCAP_POSE_URL = '/examples/test_pose.mcap';
export const MCAP_3CAM_URL = '/examples/test_3cam.mcap';
export const MCAP_H264_URL = '/examples/test_h264.mcap';
export const MCAP_COMPRESSED_DEPTH_URL = '/examples/test_compressed_depth.mcap';
export const HDF5_MINIMAL_URL = '/examples/test_minimal.hdf5';
export const BVH_MINIMAL_URL = '/examples/test_minimal.bvh';
export const MCAP_MULTI_BASE_URL = '/examples/test_multi_base.mcap';
export const MCAP_MULTI_INCREMENTAL_URL = '/examples/test_multi_incremental.mcap';

/** Fail fast when pretest:e2e has not generated fixtures. */
export function requireFixture(fixturePath: string): string {
  if (!existsSync(fixturePath)) {
    throw new Error(`Missing fixture: ${fixturePath}. Run npm run gen:e2e:fixtures`);
  }
  return fixturePath;
}

export function requireExamplesDir(): void {
  requireFixture(MCAP_BASIC);
}

/**
 * Some fixtures depend on an optional external tool (the `mcap` CLI for
 * MCAP_MULTI_FILTERED, the Python `rosbags` package for BAG_MULTI) and are
 * skipped by their generator script when that tool isn't installed. Tests
 * that need one of these should check this and `test.skip()` rather than
 * fail outright.
 */
export function fixtureExists(fixturePath: string): boolean {
  return existsSync(fixturePath);
}
